all: Q1 Q3 Q4 Q6 Q7

Q1:
	nasm -g -F DWARF -felf Q1.asm
	gcc -m32 -g -o Q1 Q1.o

Q3:
	nasm -g -F DWARF -felf Q3.asm
	gcc -m32 -g -o Q3 Q3.o

Q4:
	nasm -g -F DWARF -felf Q4.asm
	gcc -m32 -g -o Q4 Q4.o

Q6:
	nasm -g -F DWARF -felf Q6.asm
	gcc -m32 -g -o Q6 Q6.o

Q7:
	nasm -g -F DWARF -felf Q7.asm
	gcc -m32 -g -o Q7 Q7.o
