all: add_2_nums add_two_number hello_world print_largest print_name print_odd_even reading_and_printing two_digit_sum

add_2_nums:
	nasm -f elf add_2_nums.asm
	ld -melf_i386 add_2_nums.o -o add_2_nums

add_two_number:
	nasm -f elf add_two_number.asm
	ld -melf_i386 add_two_number.o -o add_two_number

hello_world:
	nasm -f elf hello_world.asm
	ld -melf_i386 hello_world.o -o hello_world

print_largest:
	nasm -f elf print_largest.asm
	ld -melf_i386 print_largest.o -o print_largest

print_name:
	nasm -f elf print_name.asm
	ld -melf_i386 print_name.o -o print_name

print_odd_even:
	nasm -f elf print_odd_even.asm
	ld -melf_i386 print_odd_even.o -o print_odd_even

print_sequence:
	nasm -f elf print_sequence.asm
	ld -melf_i386 print_sequence.o -o print_sequence

printing_n_numbers:
	nasm -f elf printing_n_numbers.asm
	ld -melf_i386 printing_n_numbers.o -o printing_n_numbers

print_odd_even:
	nasm -f elf print_odd_even.asm
	ld -melf_i386 print_odd_even.o -o print_odd_even

reading_and_printing:
	nasm -f elf reading_and_printing.asm
	ld -melf_i386 reading_and_printing.o -o reading_and_printing

two_digit_sum:
	nasm -f elf two_digit_sum.asm
	ld -melf_i386 two_digit_sum.o -o two_digit_sum
